//
//  Translations.swift
//  colt
//
//  Created by Angie Sanders on 8/21/20.
//

import Flynn
import Foundation

class Translations: Actor {
    private var translations: [String: String] = [:]
    
    private func _beStoreTranslation(_ key: String, _ value: String) {
      translations[key] = value
    }
    
    public func unsafeGetTranslations() -> [String: String] {
        return translations
    }
}



// MARK: - Autogenerated by FlynnLint
// Contents of file after this marker will be overwritten as needed

extension Translations {

    @discardableResult
    public func beStoreTranslation(_ key: String, _ value: String) -> Self {
        unsafeSend { self._beStoreTranslation(key, value) }
        return self
    }

}
